### ISSUE TITLE
Problems encountered in the Full Defect Workflow Example (w/GGA) section

### ISSUE THREAD

**Issue by zhangweiteng** [SMTG-Bham/doped#101]
Sorry to bother you in your busy schedule! I was having trouble learning the Parse host structure in the Full Defect Workflow Example (w/GGA) section, the python script was having trouble executing and the subsequent kgrid package was not successfully installed on the server. Please give me a precious answer at your convenience, thank you!

**Comment by ireaml** [comment]
Hi @zhangweiteng. Thanks for your interest in doped.
What type of errors did you get when parsing the structure and installing kgrid? Providing the error messages you got helps us to understand what might be causing the issue.

* I just tried installing `kgrid` on a new environment and worked fine so the installation issue might be related to the server you're using? 
* Regarding parsing the structure, I just tried the tutorial and worked fine once I installed the package `emmet-core`, as automatically suggested by `doped` once you try to run the following cell:
```
from doped.utils.symmetry import get_primitive_structure
prim_struc = get_primitive_structure(mgo_entry.structure)  # get a clean primitive structure
```
which outputs:
`Your Materials Project (MP) API key (either ``api_key`` parameter or 'PMG_MAPI_KEY' in ``~/.pmgrc.yaml`` or ``~/.config/.pmgrc.yaml``) corresponds to the new MP API, which requires emmet-core and mp-api as dependencies, but these are not both installed. Please install with ``pip install -U mp-api emmet-core``!`
and then runs fine once you install `emmet-core`.

To run the tutorial, I'd recommend installing doped from the `develop` branch, since there are some updates to this tutorial that haven't been published in the `main` branch yet (see [related issue](https://github.com/SMTG-Bham/doped/issues/100)). You can install the `develop` branch as mentioned [here](https://github.com/SMTG-Bham/doped/issues/100) by doing:
```
git clone https://github.com/SMTG-Bham/doped.git
git checkout develop
conda activate <your_conda_environment>
pip install -e .
```

**Comment by zhangweiteng** [comment]
> Hi @zhangweiteng. Thanks for your interest in doped. What type of errors did you get when parsing the structure and installing kgrid? Providing the error messages you got helps us to understand what might be causing the issue.
> 
> * I just tried installing `kgrid` on a new environment and worked fine so the installation issue might be related to the server you're using?
> * Regarding parsing the structure, I just tried the tutorial and worked fine once I installed the package `emmet-core`, as automatically suggested by `doped` once you try to run the following cell:
> 
> ```
> from doped.utils.symmetry import get_primitive_structure
> prim_struc = get_primitive_structure(mgo_entry.structure)  # get a clean primitive structure
> ```
> 
> which outputs: `` Your Materials Project (MP) API key (either ``api_key`` parameter or 'PMG_MAPI_KEY' in ``~/.pmgrc.yaml`` or ``~/.config/.pmgrc.yaml``) corresponds to the new MP API, which requires emmet-core and mp-api as dependencies, but these are not both installed. Please install with ``pip install -U mp-api emmet-core``! `` and then runs fine once you install `emmet-core`.
> 
> To run the tutorial, I'd recommend installing doped from the `develop` branch, since there are some updates to this tutorial that haven't been published in the `main` branch yet (see [related issue](https://github.com/SMTG-Bham/doped/issues/100)). You can install the `develop` branch as mentioned [here](https://github.com/SMTG-Bham/doped/issues/100) by doing:
> 
> ```
> git clone https://github.com/SMTG-Bham/doped.git
> git checkout develop
> conda activate <your_conda_environment>
> pip install -e .
> ```

Thank you very much for your valuable reply! I have successfully installed the kgrid package after publishing the issue. I tried installing doped from the develop branch, but it was unsuccessful. If the main in the doped package is going to be updated soon, I can wait for the doped update. Meanwhile, I am looking forward to the update of the version and would like to express my sincere gratitude once again for your reply!

**Comment by kavanase** [comment]
Great! If you've successfully installed `kgrid` now then your issue should be solved. You don't need to wait for a `doped` update as it seems your issue is not related to any version updates.
Happy coding, and thanks @ireaml for handling this!
