### ISSUE TITLE
How to use `extrinsic` to generate deuterium/OH/ions defects? 

### ISSUE THREAD

**Issue by Nour-Aldein2** [SMTG-Bham/doped#51]
I'm trying to study generate deuterium, OH, and ionic (e.g. substitute charged O atom in Si location) defects using doped. I'm assuming that I should be using `extrinsic` in `DefectsGenerator` to do so, however, that did not work.

**Comment by kavanase** [comment]
HI @Nour-Aldein2!
Yes for deuterium and oxygen substitution, you just need to specify these as extrinsic species for your material using the `extrinsic` parameter. Deuterium is the same as Hydrogen when it comes to DFT calculations in VASP, apart from MD and phonon calculations where the mass difference matters, and so this can just be set as `"H"` as such:
<img width="669" alt="image" src="https://github.com/SMTG-Bham/doped/assets/51478689/56f282d2-cc16-4d0b-b23e-5ab5d97d0eec">

(And then if you're following this up with phonon/MD calculations, you would then just need to adjust `POMASS` in the `H` `POTCAR` as discussed here: https://www.vasp.at/forum/viewtopic.php?t=71)

Here you can see it has also generated the O-on-Si substitution you mentioned, in a range of possible charge states (which you can also adjust if needed).

For OH substitution, because this is a complex and it would involve some choice of how the OH molecule is oriented, this is not automated in `doped`. I would suggest you take the corresponding oxygen interstitial/substitution defect supercell generated by `doped`, and then manually place H where you expect it to be (or trial a few different configurations). There are many tools for this, and can be done fairly easily within the `pymatgen` objects from `doped`. You could then use these structures with the `DefectDictSet` object from `doped.vasp` to generate the corresponding input files, or generate them manually / copy from other defects and update `NELECT` & `NUPDOWN` accordingly. 

Also just to note in general, if you are having some issue with the code, please share an example of what the actual issue is (instead of "that did not work"), as unfortunately I'm not psychic so can't diagnose a specific issue based on just that.

Hope that helps!

**Comment by kavanase** [comment]
Hi @Nour-Aldein2,
Yes this is entirely possible, and is what is shown in my screenshot above (and in the tutorials on the docs). You just need to provide your Si matrix structure and specify `extrinsic= "O"` (as shown above), then doped will generate this defect (amongst other possibilities) and give a set of "guessed" likely charge states. 
You can then add/remove charge states with the `DefectsGenerator.add/remove_charge_states()` method as shown in the generation tutorial, if desired.

**Comment by kavanase** [comment]
Just to note, `O_Si^+1` sounds like quite an unlikely charge state.
While I don't agree with some of their message, it might be worth a ready of this paper which discusses the differences between absolute and relative defect charges (we always use relative): https://www.nature.com/articles/s41563-023-01583-4
And then this paper is the classic review on general defect calculations: 10.1103/RevModPhys.86.253

**Comment by Nour-Aldein2** [comment]
Thank you for your answer, @kavanase. I will close this issue for now, and if there's anything in the future, I hope you don't mind if I reopen it.
