### ISSUE TITLE
error in ExtrinsicCompetingPhases module 

### ISSUE THREAD

**Issue by similt** [SMTG-Bham/doped#57]
Dear Team, 
I get below error when running an example calculation: 
Do you know how to resolve this error? 

from doped.chemical_potentials import ExtrinsicCompetingPhases
ex_cp = ExtrinsicCompetingPhases(composition="ZrO2", extrinsic_species="La", e_above_hull=0.03)

The 'inc_structure' argument is deprecated as structure data is now always included in all returned entry objects.
Retrieving ThermoDoc documents: 100%|█████████████████████████████████████████████| 59/59 [00:00<00:00, 558609.34it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aaa/Downloads/miniconda3/lib/python3.11/site-packages/doped/chemical_potentials.py", line 810, in __init__
    super().__init__(composition, e_above_hull, api_key)
  File "/home/aaa/Downloads/miniconda3/lib/python3.11/site-packages/doped/chemical_potentials.py", line 399, in __init__
    self.MP_full_pd_entries = mpr.get_entries_in_chemsys(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaa/Downloads/miniconda3/lib/python3.11/site-packages/mp_api/client/mprester.py", line 1192, in get_entries_in_chemsys
    self.get_entries(
  File "/home/aaa/Downloads/miniconda3/lib/python3.11/site-packages/mp_api/client/mprester.py", line 759, in get_entries
    doc.model_dump()[property]  # type: ignore
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'pretty_formula'

**Comment by kavanase** [comment]
Hi @similt!
I think here you are using the new `Materials Project` API, rather than the legacy API?
At present, `doped` uses the legacy API (we found some issues with mis-labelling of energies-above-hull in the new API/database), but we plan on updating to support the current API in the very near future. 

![image](https://github.com/SMTG-Bham/doped/assets/51478689/9e30cfaa-a5d5-40f3-a681-a0a02c267c6a)

If this solves your issue, please let me know! I'll bump this issue when support for the new API is added, but for now supplying a legacy API key should fix this.

**Comment by similt** [comment]
Hi @kavanase, Thank you for quick support. With Legacy API, program command " ex_cp = ExtrinsicCompetingPhases(composition="ZrO2", extrinsic_species="La", e_above_hull=0.03)"  is working.
