### ISSUE TITLE
Extrinsic Competing Phases error

### ISSUE THREAD

**Issue by similt** [SMTG-Bham/doped#60]
Why am I getting error while generating competing phase diagram with external impurity?
In material project there is an entry Cs2CuBiI6

x_cp = ExtrinsicCompetingPhases(composition="Cs3Cu3I5", extrinsic_species="Bi", e_above_hull=0.03)
You are using the legacy MPRester. This version of the MPRester will no longer be updated. To access the latest data with the new MPRester, obtain a new API key from https://materialsproject.org/api and consult the docs at https://docs.materialsproject.org/ for more information.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/aaa/miniconda3/lib/python3.12/site-packages/doped/chemical_potentials.py", line 810, in __init__
    super().__init__(composition, e_above_hull, api_key)
  File "/scratch/aaa/miniconda3/lib/python3.12/site-packages/doped/chemical_potentials.py", line 444, in __init__
    bulk_ce = bulk_entries[0]  # lowest energy entry for bulk composition (after sorting)
              ~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by kavanase** [comment]
Hi @similt,
The error here is due to the fact the bulk composition you've given (`Cs3Cu3I5`) doesn't exist in the Materials Project:
![image](https://github.com/SMTG-Bham/doped/assets/51478689/be26e14c-082d-4f7a-971b-ac04eba6a4d2)

I'm working on making the errors for this part of the code a bit more informative btw.

**Comment by similt** [comment]
Thanks, @kavanase, for the information.
