### ISSUE TITLE
Parsing issues

### ISSUE THREAD

**Issue by msehabibur** [SMTG-Bham/doped#63]
Hi, thank you for developing such tool. When I wanted to parse the output, it was throwing out this error messages 
<img width="1100" alt="Screenshot 2024-04-19 at 4 32 18 PM" src="https://github.com/SMTG-Bham/doped/assets/96934016/9739d2e4-984b-4c8b-bdfc-1b9b64031af9">
This is my script to parse the output....

from doped.analysis import DefectsParser

dielectric = 8.99  # dielectric constant (this can be a single number (isotropic), or a 3x1 array or 3x3 matrix (anisotropic))
bulk_path='/depot/amannodi/data/Benji_Sabria_Calculations_Folder/Sabria/CdTe/Ground_State_POSCAR/bulk/vasp_std'
dp = DefectsParser('/depot/amannodi/data/Benji_Sabria_Calculations_Folder/Sabria/CdTe/Ground_State_POSCAR/', dielectric=dielectric)  # dielectric needed for charge corrections

Under '/depot/amannodi/data/Benji_Sabria_Calculations_Folder/Sabria/CdTe/Ground_State_POSCAR/', I have bunch of defect folders 
<img width="1133" alt="Screenshot 2024-04-19 at 4 35 52 PM" src="https://github.com/SMTG-Bham/doped/assets/96934016/c17570e6-f149-44cd-a3d7-cd4889140ab3">

**Comment by kavanase** [comment]
You need to post the full error traceback for me to figure out the issue here.

If that is the folder structure in that folder, then it should be fine, but I can't actually see what's in these folders. Also it looks like you might be using an older version of `doped` as well.

**Comment by msehabibur** [comment]
Hi Sean, I just updated the version, though it still shows the error. Does it expect every output file inside the 'vasp_std' folder? Here are some snapshots so that you can gain more insight. @kavanase 

<img width="1792" alt="Screenshot 2024-04-19 at 7 35 44 PM" src="https://github.com/SMTG-Bham/doped/assets/96934016/303f042c-75f4-46b0-9310-7118f7b9ee9b">
<img width="1245" alt="Screenshot 2024-04-19 at 7 36 28 PM" src="https://github.com/SMTG-Bham/doped/assets/96934016/c021871f-f509-4e77-af5c-3e522de1c8fe">
<img width="1315" alt="Screenshot 2024-04-19 at 7 36 46 PM" src="https://github.com/SMTG-Bham/doped/assets/96934016/009a8c9c-3c33-47ce-b6b2-0bf5e1503f98">
<img width="1136" alt="Screenshot 2024-04-19 at 7 39 31 PM" src="https://github.com/SMTG-Bham/doped/assets/96934016/a05fcabf-5ec2-4b79-91cd-04d2b1583e45">

**Comment by kavanase** [comment]
Yeah so it's the errors above (that say `Parsing failed for...`) that are telling you why the defects are failing to parse.
<img width="1384" alt="image" src="https://github.com/SMTG-Bham/doped/assets/51478689/4b107003-884b-4c05-be3a-27af7bac6478">

For the `ParseError` ones, that indicates a `vasprun.xml(.gz)` parsing error. From the output, it's suggesting there's either not a vasprun present in those directories listed in the error message, or it's an empty/corrupted `vasprun.xml` present.

For the other `AttributeError`, I haven't seen that before, from anyone else or in our tests. From digging through the code to see what could be causing this, I _think_ this could be caused by you setting different `INCAR` tags for something in your bulk and defect `INCAR`s (which is bad practice and gives unreliable results). Usually `doped` catches this and warns you, but I think here you have a string value set in one case (e.g. `LREAL = Auto`) and a boolean for the other (e.g. `LREAL = False`), which in this rare case is causing a failure.

**Comment by kavanase** [comment]
I updated the code to automatically handle this edge case where mismatching types are used for the values in your bulk and defect `INCAR`s, in https://github.com/SMTG-Bham/doped/commit/7a71845f3ace17b89d623f754e58a5a49df0079b
If you do `pip install https://github.com/SMTG-Bham/doped/archive/develop.zip`, this should install this version of the code and avoid that failure in your code – but as desired it will throw warnings about your mismatching tags, saying that this will cause errors

**Comment by msehabibur** [comment]
@kavanase I just did `pip install https://github.com/SMTG-Bham/doped/archive/develop.zip` but still saw the same error messages!
<img width="1780" alt="Screenshot 2024-04-20 at 4 44 47 PM" src="https://github.com/SMTG-Bham/doped/assets/96934016/989f4b4d-9fb8-46b9-b276-f021225ed0ef">

**Comment by kavanase** [comment]
Are you sure your script is using the correct updated `doped`? I see you're using a conda environment. I would double check the new version of `doped` is actually being installed here (it might help to fully uninstall `doped` before reinstalling).
I have checked again and I don't see where else this error could be coming from. Did you check the differences in `INCAR`s between your bulk and defect calculations?

I would note you also set your bulk path to `.../bulk/vasp_std` but `bulk/vasp_std` doesn't exist based on the screenshots you shared (but `doped` then adjusts and automatically identifies the correct `bulk` directory).

**Comment by msehabibur** [comment]
Hi I just did pip uninstall doped from my conda environment and then did `pip install https://github.com/SMTG-Bham/doped/archive/develop.zip` This is the Python script I am using to parse the output. 

```
from doped.analysis import DefectsParser
dielectric = 8.99  # dielectric constant (this can be a single number (isotropic), or a 3x1 array or 3x3 matrix (anisotropic))
bulk_path='/depot/amannodi/data/Benji_Sabria_Calculations_Folder/Sabria/CdTe/Ground_State_POSCAR/bulk/vasp_std/'
dp = DefectsParser(
    output_path="/depot/amannodi/data/Benji_Sabria_Calculations_Folder/Sabria/CdTe/Ground_State_POSCAR/",  # directory containing the defect calculation folders
    dielectric=dielectric,  # dielectric needed for charge corrections
    processes=1,  # Can set the number of processes to 1 if you're having issues with multiprocessing
)
```

**Comment by msehabibur** [comment]
My depot/amannodi/data/Benji_Sabria_Calculations_Folder/Sabria/CdTe/Ground_State_POSCAR/bulk/vasp_std/

<img width="1313" alt="Screenshot 2024-04-20 at 6 34 02 PM" src="https://github.com/SMTG-Bham/doped/assets/96934016/6566e77a-36c8-4e43-8dcc-40ad99e53057">

**Comment by msehabibur** [comment]
I also did the bulk calculations again using the same INCAR settings as the defect calculations.

**Comment by kavanase** [comment]
Ok I can't see where else in the code this could be coming from. Can you share the `vasprun.xml.gz` files for your bulk calculation, and for one defect calculation each from the two sets of parsing failings shown in the screenshot (e.g. `Te_Cd_-1` and `Te_Cd_+1`) so I can find the origin?

**Comment by msehabibur** [comment]
Sure
[Uploading bulk.zip…]()
[Uploading Te_Cd_-1.zip…]()
[Uploading Te_Cd_+1.zip…]()

**Comment by kavanase** [comment]
Ok I checked with these files. I can't reproduce this error, so it seems like for some reason your code is still using the older `doped` version. 
I did notice an issue that was being caused by the fact that your bulk vasprun here has `NUPDOWN = 1` which is presumably a mistake, so this is better handled in the latest version of the `doped` `develop` branch. But this shouldn't cause the original error you posted above.

<img width="837" alt="image" src="https://github.com/SMTG-Bham/doped/assets/51478689/e62b1e8c-474e-4352-a02c-d1c50c8a6d24">
