### ISSUE TITLE
Point defect generation in ternary alloy 

### ISSUE THREAD

**Issue by msehabibur** [SMTG-Bham/doped#64]
I am currently trying to generate point defects in a Zn_108Se_27Te_81 alloy using a 3x3x3 supercell configuration of the zinc blende crystal structure, which comprises a total of 216 atoms. However, the output from the `doped` has been unexpected and appears to deviate from anticipated results.

Based on the output data, it seems there may be a considerable number of non-equivalent defect sites within the structure, which could be influencing the behavior of the `DefectGeneration` class, triggering unexpected results. This observation suggests potential issues in the symmetry or initial configuration of the supercell that may need to be addressed.

Could you please review the attached file and provide your insights on whether the presence of these non-equivalent defect sites might be affecting the `doped `outcomes? Your expertise in this area would be invaluable in diagnosing and resolving this issue.

Also, I would suggest

1. Refactoring respective Class capable of adaptively placing defects based on the local atomic environment, rather than a uniform approach. This would allow the class to manage non-equivalent sites more effectively by adjusting the defect characteristics to match the unique aspects of each site.

2. Consider implementing machine learning (https://github.com/materialsvirtuallab/matgl) techniques to quickly identify the equivalent sites and high energy defects 

Thank you for your assistance.

Best regards,
Habibur

[POSCAR.zip](https://github.com/SMTG-Bham/doped/files/15057576/POSCAR.zip)
[file.zip](https://github.com/SMTG-Bham/doped/files/15057577/file.zip)

**Comment by kavanase** [comment]
Yes in a disordered material there are now many inequivalent sites due to the broken symmetry. This is fully expected and the symmetry functions in `doped` are working as expected for this. This is why you can't just do single defect calculations in a disordered/alloyed material like you can with a pristine high symmetry host. 

>Refactoring respective Class capable of adaptively placing defects based on the local atomic environment, rather than a uniform approach. This would allow the class to manage non-equivalent sites more effectively by adjusting the defect characteristics to match the unique aspects of each site.

This makes no sense to me. 

>Consider implementing machine learning (https://github.com/materialsvirtuallab/matgl) techniques to quickly identify the equivalent sites and high energy defects

Machine learning is not needed to "identify equivalent sites". `doped` does this automatically – it's exactly what it's doing in this case – using symmetry. 
Machine learning could be used to identify high energy defects, but my time is finite so I can't just devote it entirely to making defect calculations as easy and mindless as possible for the user, and either way this can typically be achieved by basic chemical intuition on the basis of ionic radii and oxidation state preferences. Also high energy defects can still be relevant for certain applications / full system characterisation.

**Comment by msehabibur** [comment]
@kavanase thanks for clarification! Is there any way to expedite the defect generation process? It takes a lot of time!!

**Comment by kavanase** [comment]
The defect generation process for a disordered cell is slow because there is low symmetry and a large supercell. The generation process in `doped` is heavily expedited and is orders of magnitude faster than in other defect codes (most of them will crash if you input this structure to them). 

There are some further options to expediting this process – which are listed in the documentation, tutorials and docstrings for this. For your convenience, these include multiprocessing (so if you run on a good laptop or HPC it will be much faster), or skipping interstitial generation if these are not desired. I would also note that defect generation only needs to be done once (if done correctly).

**Comment by msehabibur** [comment]
@kavanase Thanks! One last question in this loop: may I know how you created this animation? Any Python tool, possibly? Thanks again!

[
<img width="708" alt="Screenshot 2024-04-23 at 11 14 23 AM" src="https://github.com/SMTG-Bham/doped/assets/96934016/e36842be-e581-4b73-a2db-98f2223997fc">
](url)

**Comment by kavanase** [comment]
I used PowerPoint for that one. You can export slides as GIFs. I've also used ImageMagick for other GIFs
