### ISSUE TITLE
Reducing number of substitutions defects

### ISSUE THREAD

**Issue by msehabibur** [SMTG-Bham/doped#65]
Is there any way to reduce the number of substitutional defects @kavanase like interstitial?

**Comment by alexsquires** [comment]
Doped will enumerate all symmetrically independent defects. Interstitials are a special case because only in the simplest crystal structures can they be unambiguously defined, hence the finer control over the interstitial generation.

If you only want to run DFT calculations on a subset of the substitutional defects, that is a user decision which you will want to justify based on the chemistry of the system. An example may be assuming that cation-on-anion (and vice versa) substitutional defects will be high in energy in highly ionic systems.

Note that every defect you excluded from your DFT calculations makes the calculated defect concentrations and self-consistent Fermi energy an increasingly crude approximation of the real defect chemistry of the system.

**Comment by adair-nicolson** [comment]
Hi @msehabibur, to provide some additional advice on studying interstitials:

```Doped``` uses Voronoi tessellation by default to identify potential interstitial sites. This can, depending on your bulk structure, result in a large number of trial interstitial structures. In the Tips and Tricks section of the docs [https://doped.readthedocs.io/en/latest/Tips.html#interstitials](https://doped.readthedocs.io/en/latest/Tips.html#interstitials)  we provide some advice on how to prune down the number of candidates. We have found the techniques listed to be very effective in reducing the computational cost of studying interstitial defects.

If you know the coordinates of a specific site you want to study you can provide the coordinates when generating your defects using ```interstitial_coords```. Additional methods to customise the defect generation process can be found in the [API docs](https://doped.readthedocs.io/en/latest/doped.generation.html#doped.generation.DefectsGenerator).

Hope this helps!

**Comment by msehabibur** [comment]
@alexsquires @kavanase may I ask the difference between As_Se_C1_Zn2.87Se4.69Te4.69a_0 and As_Se_C1_Zn2.87Se4.69Te4.69b_0 in Zn_108Se_36Te_72 alloy? And, what does it mean by Zn2.87Se4.69Te4.69?? Thanks!

**Comment by kavanase** [comment]
This is explained in the `doped` tutorials, API docs and docstrings:
https://doped.readthedocs.io/en/latest/generation_tutorial.html#defect-generation

<img width="646" alt="image" src="https://github.com/SMTG-Bham/doped/assets/51478689/e3a058d8-7eb0-450f-b2d6-d88776a751f6">
<img width="706" alt="image" src="https://github.com/SMTG-Bham/doped/assets/51478689/70e9665c-df30-4784-ad58-6a00e9d7f523">

So they are the nearest neighbours and their distances in Angstrom, which are given until a unique defect name is found for that (symmetry-inequivalent, as we discussed before) site. If it's still not unique after including 3 neighbours as in this case, then `doped` will append `a`, `b`, `c` etc labels to differentiate these sites. 

There is a search button on the `doped` docs. Searching "defect names" immediately shows where this is mentioned/discussed in the tutorials and code. Please check this and other immediately-available resources first before taking time from the developers.
