### ISSUE TITLE
Regarding selecting a supercell

### ISSUE THREAD

**Issue by rushikd27** [SMTG-Bham/doped#82]
I recently used dope to generate defects for a system and noticed that it didn't use the same supercell the second time around for the same system and the exact same input structure.

Do you know why this can happen since this would restrict the reproducibility of results?

**Comment by kavanase** [comment]
Hi @rushikd27, this is odd and shouldn't happen.
The algorithms for structure generation in `doped` are built to be deterministic, so the same input structure should give the exact same supercell output – _assuming the same version of `doped` was used._ We have many tests for checking this is the case, and we've never seen anything different happen.

What can occasionally happen, is that an update to the supercell generation algorithm in a newer version of `doped` gives a different output structure to a previous version of `doped`. As with all codes there are slight differences between versions as new functionality and performance improvements are added, so for full reproducibility when reporting results, it's important to note the code version number that was used. However, the main changes to the code with each version are always listed in the [change log](https://doped.readthedocs.io/en/latest/changelog_link.html), and changes are almost always made to be backwards-compatible, so if you wanted to reproduce the supercell generated with a previous version then it should just be a case of setting some of the `supercell_gen_kwargs` parameters (see [docstring](https://doped.readthedocs.io/en/latest/doped.generation.html#doped.generation.DefectsGenerator) and [advanced tutorial](https://doped.readthedocs.io/en/latest/advanced_analysis_tutorial.html#enforced-near-cubic-supercell)) rather than using the defaults – though whatever supercell is output by the latest version of `doped` should be the 'better' one.
I suspect this is likely the case here. You don't give any details here of what the structure is, what code was used to generate the supercell etc, so it's hard to diagnose further. Does this solve your issue?

**Comment by rushikd27** [comment]
Hi Sean,

Thanks for your comment. i also suspected it might be due to version changed but raised an issue just in case it happened to someone else.

I apologise for not mentioning the details of the structure.

It was a BaZrS3 cell with 20 atoms (lattice parameters: 7, 7, 10 A, orthorhombic) when I did it initially using an older version (don’t exactly remember the version number but I know I updated the code before trying it again) it generated a 2x2x1 supercell but the second time it generated a complex geometry which was not 2x2x1.

But I believe it is purely due to the use of different versions.

**Comment by kavanase** [comment]
Ok cool! 
Yes this should then be due to the use of a version <`2.3.0` (released 14/2/24) before, and >=`2.3.0` after. 
Previously `doped` used the default `pymatgen` near-cubic supercell generation scheme, but then we implemented the greatly improved scheme discussed in the [JOSS paper](https://joss.theoj.org/papers/10.21105/joss.06433) which directly optimises the minimum periodic image distance of the supercell, which often gives non-diagonal expansion matrices which achieve the same defect-defect distances but for reduced numbers of atoms in the supercell (thus reduced cost).

In this case, BZS with the default gives you the non-diagonal 60-atom supercell expansion for the default minimum image distance threshold of 10 Å:
<img width="637" alt="image" src="https://github.com/SMTG-Bham/doped/assets/51478689/e11d975c-3c33-4aa0-bdd5-8c601b865290">

But if you set `force_cubic` to `True`, it will revert to the previous generation scheme to give you the same 80-atom 2x2x1 supercell:
<img width="767" alt="image" src="https://github.com/SMTG-Bham/doped/assets/51478689/9ea0e00e-76b1-4489-887a-9ecadf27fb7d">

**Comment by rushikd27** [comment]
Thanks again for this comment. This seems like an interesting approach to increasing computational efficiency.
